[[constraint]]
  branch = "master"
  name = "github.com/fluent/fluent-bit-go"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"